name: localization
description: "Localization layer of the application, providing translations and locale management."
version: 0.0.1
homepage:

resolution: workspace

environment:
  sdk: ^3.8.1
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sheety_localization: ^0.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0